from __future__ import annotations

import hashlib
from collections.abc import Sequence

from app.agents.base import AgentResult
from app.github.client import GitHubClient
from app.github.models import PullRequestRef
from app.logging import get_logger

log = get_logger(__name__)

BOT_MARKER = "<!-- pr-agent-review-bot -->"


def severity_icon(level: str) -> str:
    level = level.lower()
    if level == "critical":
        return "Critical"
    if level == "high":
        return "High"
    if level == "medium":
        return "Medium"
    if level == "low":
        return "ℹLow"
    return "ℹInfo"


def build_comment(pr_url: str, head_sha: str, results: Sequence[AgentResult]) -> str:
    total_findings = sum(len(r.findings) for r in results)
    score = max(0, 10 - total_findings)

    lines: list[str] = []
    lines.append(BOT_MARKER)
    lines.append("# AI Multi-Agent Code Review Report")
    lines.append("")
    lines.append(f"### Overall Score: **{score} / 10**")
    lines.append("")
    lines.append(f"- PR: {pr_url}")
    lines.append(f"- Commit: `{head_sha[:12]}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    for r in results:
        lines.append(f"## {r.agent_name}")
        lines.append("")
        lines.append(r.summary)
        lines.append("")

        if r.findings:
            lines.append("| Severity | Title | Details |")
            lines.append("|----------|-------|---------|")

            for f in r.findings:
                lines.append(
                    f"| {severity_icon(f.severity)} | {f.title} | {f.details} |"
                )

        else:
            lines.append("No issues detected.")

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("### Review Metadata")
    lines.append("")
    lines.append(f"- Fingerprint: `{comment_fingerprint(head_sha)}`")
    lines.append("- Generated by PR Agent Review Bot")
    lines.append("")
    lines.append(
        "_If something looks incorrect, reply to this comment and tag the repository owner._"
    )

    return "\n".join(lines).strip() + "\n"

def comment_fingerprint(head_sha: str) -> str:
    # Used for idempotency: per head SHA, we post at most one comment.
    return hashlib.sha256(head_sha.encode("utf-8")).hexdigest()[:12]


async def already_commented_for_sha(gh: GitHubClient, pr: PullRequestRef, head_sha: str) -> bool:
    fp = comment_fingerprint(head_sha)
    comments = await gh.list_issue_comments(pr)
    for c in comments:
        raw_body = c.get("body")
        body = raw_body if isinstance(raw_body, str) else ""
        if BOT_MARKER in body and fp in body:
            return True
    return False


def attach_fingerprint(body: str, head_sha: str) -> str:
    fp = comment_fingerprint(head_sha)
    return body + f"\n\n`fingerprint:{fp}`\n"
